naming:
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*'
  PackageNaming:
    active: true
    packagePattern: '[a-z]+(\.[a-z][A-Za_za-z0-9]*)*'

complexity:
  LongParameterList:
    functionThreshold: 20
    ignoreDefaultParameters: true

style:
  MagicNumber:
    active: false
    ignorePropertyDeclaration: true
  DataClassShouldBeImmutable:
    active: false
  UnusedPrivateMember:
    ignoreAnnotated: [ 'Preview' ]
  MaxLineLength:
    active: false
  WildcardImport:
    active: false